### ISSUE TITLE
Just a question: do something when user swipe notification instead of pressing it

### ISSUE THREAD

**Issue by SlimenTN** [mitchhymel/local_notifications#22]
I wanted to know is it possible to call a function when user swipe notificaiton without pressing it ?
something smilar to `onSelectNotification`.
I want to know if user pressed the notification or dissmissed it.

**Comment by mitchhymel** [comment]
That functionality is not currently supported by this plugin and I'm not actively working on this plugin anymore.

From a quick search, it looks like it's [technically possible on android](https://stackoverflow.com/a/49377788). I.E. to implement this functionality in this plugin, one would need to add something like ```onDismissNotification``` that would essentially be implemented the same as ```onSelectNotification```, but in the android code use ```setDeleteIntent``` instead of ```setContentIntent```. I don't have much iOS experience, so I can't say definitively if this behavior can be implemented there.

**Comment by SlimenTN** [comment]
thanks for your answer but a notification plugin is very useful hope you back to work on it again.
